---
title: "Software Architecture Radio"
baseURL: "https://softwarearchitecturerad.io/"
theme: "zen"
languageCode: "en-US"
defaultContentLanguage: "en"
pluralizelisttitles: false
removePathAccents: true
paginate: 10
paginatePath: "page"
rssLimit: 20

author:
  name: "Matt Stine"
  url: "https://mattstine.com"
  avatar: "/images/matt.jpg"

outputFormats:
  SearchIndex:
    mediaType: "application/json"
    baseName: "searchindex"
    isPlainText: true
    notAlternative: true

outputs:
  home: ["HTML","RSS", "JSON", "SearchIndex"]
  section: ["HTML","RSS", "JSON"]

params:
  contact: "info@example.org"
  copyright: "<!--Creative Commons License-->This site is licensed under a [Creative Commons Attribution-ShareAlike 4.0 International License](https://creativecommons.org/licenses/by-sa/4.0/).<!--/Creative Commons License-->"
  description: "The zen theme for Hugo example site."
  dateformat: "2 January, 2006"
  favicon: "apple-touch-icon.png"
  realfavicongenerator: true
  themeColor: "#87b8f2"
  safariPinnedColor: "#87b8f2"
  feedlinks: true
  footer: "Copyright &copy;2020 Matt Stine. Logo is Software Architecture by Richard Slater from the Noun Project. Powered by [Hugo](https://gohugo.io/) and the [Zen theme](https://github.com/frjo/hugo-theme-zen)."
  icon: "apple-touch-icon.png"
  image: "apple-touch-icon.png"
  logo: true
  imageMaxWidth: 400
  mobileMenu: true
  poweredby: false
  sidebar: false
  submitted: true

permalinks:
  episodes: "/:year/:month/:day/:title"